#+AUTHOR: Harshad Shirwadkar
#+EMAIL: harshad@cmu.edu

* Network layer objects
** Idea
- /OID is a new XIA principle/
- Network layer exposes object APIs to applications
- Network layer forms objects by creating a rootchunk that points to
  all other chunks
- OID is the CID of the rootchunk
- Network layer adds OID to the chunk header in every chunk in that
  object
** Diagram
[[./img/oid-d2-nwlayer.pdf]]
** Note
This design is very similar to the last design of object library. All
the pros and cons in the object library design apply here as well. The
main distinguishing factor between these two designs is the placement
of OIDs. In this design, OID is a new principle type. This allows us
to perform network layer tasks such as routing, caching at the object
granularity. This new ability allows us to have following advantages:

- Routing and forwarding, if performed at object granularity, can
  significantly reduce the size of FIB
- We will also need reliablility at the object layer. If a network
  entity /can/ say that "I have this OID", then, instead of opening
  multiple stream connections to fetch individual CIDs in an object,
  the consumer may be able to multiplex one transport connection to
  fetch the entire object. Note that, this is not possible in the
  earlier design, since in that design the network does not know what
  is an object. So, installing OID routes was not possible in that
  design.
